# -*- coding: utf-8 -*-
"""cQuant.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Iza62SgGNWhd5xsP2FeBjsBgKrQDa9jD

## **cQaunt.io**

**Import file from GIT**
"""

url = 'copied_raw_GH_link'
df1 = pd.read_csv(url)
# Dataset is now stored in a Pandas Dataframe

"""**Import file from desktop to Colab:**"""

#import packages to use
from google.colab import files
#importing pandas library
import pandas as pd

data = files.upload()

#IO enables python's facilities to deal with various i/o types

import io
df = pd.read_csv(io.BytesIO(data['internal_all.csv']))



#first column of dataframe:
df[df.columns[0]]

#number of unique entries in frist column
len(pd.unique(df[df.columns[0]]))

df['Address'].describe()

df.iloc[:, :1]



"""**Import file from Drive to Colab:**"""

#import packages to use
from google.colab import files
data = files.upload()

#IO enables python's facilities to deal with various i/o types

import io
df = pd.read_csv(io.BytesIO(data['filename.csv']))



